// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jijveixmittzlexleboy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppanZlaXhtaXR0emxleGxlYm95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTczMDgsImV4cCI6MjA2MzgzMzMwOH0.WQG-zpvMwUXf9E94nCPZwwmipZRExjQ2tpEQG54k-28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);